[package]
name = "perple"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.*", features = ["full"] }
ort = "=2.0.0-rc.10"
image = { version = "0.*" }
ndarray = { version = "0.*", features = ["rayon"] }
raqote = "0.*"